name: Export Source
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        #with:
          #repository: ys56/is373
          #token: ${{ secrets.REPO_ACCESS_TOKEN }}
          #path: source

      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          repository: ys56/is373-project
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: project

      - name: Copy markdown files and images
        run: |
          cp -R source/*.md project/blog/source/_posts/
          cp -R source/images/* project/blog/source/images/

      - name: Commit and push changes
        run: |
          #cd is373-project
          cd project
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update is373-projectsite content from is373" || echo "No changes to commit"
          git push
